### ISSUE TITLE
needs better jumping script

### ISSUE THREAD

**Issue by stormchaser3000** [stormchaser3000/square#1]
the current jumping script messes up when comping to some slow computers.

**Comment by glacialcascade** [comment]
I will help, i'll remix and improve, then make an pull request.

**Comment by stormchaser3000** [comment]
ok. i did make a fix but i don't know if I pushed the commit already

**Comment by stormchaser3000** [comment]
yep i pushed a fix. sorry. but feel free to add features. i havn't worked on this for a while but i might a well.
