### ISSUE TITLE
not that related but...

### ISSUE THREAD

**Issue by glacialcascade** [stormchaser3000/square#4]
how did you add a sb2file to here?

**Comment by stormchaser3000** [comment]
um. i used git... the git command. (read more about git on a git documentation on how to use git or try using git --help)

**Comment by ninjagolloyd** [comment]
Download git on your computer. Git clone your repository. Stick the file in the directory, then push/sync it.

Or open the client, make a new repo, sick the file in, commit, then push.

**Comment by ninjagolloyd** [comment]
I will post a YouTube video soon.

**Comment by ninjagolloyd** [comment]
Look here and follow the same process. https://youtu.be/pnfqEzp0OLU

**Comment by glacialcascade** [comment]
How do you get so many options when you do new? i only get a few.

anyways, this is over

**Comment by ninjagolloyd** [comment]
I have that many repos. Fork one online or make one first.

**Comment by glacialcascade** [comment]
I mean when you rightclick and press new.
